VARIABLES IN ORACLE:
--------------------
SYNTAX:
    VARIABLE_NAME/COLUMN_NAME DATATYPE(SIZE);
    
EX:
   ID NUMBER(5);
   
   NAME VARCHAR2(20);
   
Rules for variables
---------------------
Column name must be unique

CAN NOT START WITH NUMBERS ,CAN START WITH LETTERS AND (_)UNDERSCORES ONLY.

VARIABLE NAME CONTAINS LETTERS,DIGITS AND (_,$,#)THESE SPECIAL CHARACTOR ALLOWED.



